### ISSUE TITLE
[Question] how can i install event_sync in kubernetes?

### ISSUE THREAD

**Issue by MeowSaiGithub** [jitsi-contrib/prosody-plugins#26]
Hi, I was trying out the event_sync plugin in kubernetes and event_sync is not working. I added .lua in the plugin folders and can set the api_prefix by modifying the module itself but doesn't working. Can help please?

**Comment by shawnchin** [comment]
You have already asked this in 2 different threads in the community forum. No need to repeat the same question everywhere.  You will reach the same people :)

**Comment by MeowSaiGithub** [comment]
apologies, i was just trying out different places since already stuck at this more than 8 months. thanks you tho

**Comment by shawnchin** [comment]
No problem. I understand the frustration. I only pointed this out because there aren't as many eyes in this issue tracker, and all the experts will be in the forum.

**Comment by MeowSaiGithub** [comment]
i will leave the solved threads here in-case someone found this issue - https://community.jitsi.org/t/event-sync-in-kubernetes/127751/6 thanks a lot again
