### ISSUE TITLE
is it possible to prevent an owner from leaving a meeting room when there is only one ower in the room?

### ISSUE THREAD

**Issue by NimbleDev** [jitsi-contrib/prosody-plugins#27]
i tried to hook muc-occupant-pre-leave and implemented the login as below, but it didn't work. Where am i wrong?

`module:hook("muc-occupant-pre-leave", function (event)
    local room, occupant, stanza = event.room, event.occupant, event.stanza

    if is_healthcheck_room(room.jid) or _is_admin(occupant.jid) then
        return
    end

    -- no need to do anything for normal participant
    if room:get_affiliation(occupant.jid) ~= "owner" then
        module:log(LOGLEVEL, "a participant leaved, %s", occupant.jid)
        return
    end

    -- the owner is gone, start to check the room condition
    room:broadcast_message(
        st.message({ type="groupchat", from=occupant.nick })
        :tag("body"):text("The owner is gone"))
    module:log(LOGLEVEL, "an owner leaved, %s", occupant.jid)

    -- check if there is any other owner here
    for _, o in room:each_occupant() do
        if not _is_admin(o.jid) then
            if room:get_affiliation(o.jid) == "owner" and o.jid ~= occupant.jid then
                module:log(LOGLEVEL, "an owner is here, %s", o.jid)
                return
            end
        end
    end

    -- since there is no other owner, the only owner should select a new owner before leave
    module:log(LOGLEVEL, "The only owner should select a new owner before leave");
    -- event.origin.send(st.error_reply(stanza, 'cancel', 'not-allowed',"The only owner should select a new owner before leave."))
    -- event.origin.send(st.error_reply(stanza, 'auth', 'forbidden',"The only owner should select a new owner before leave."));
    return true;

end)`

**Comment by NimbleDev** [comment]
> You cannot force someone to stay in the meeting. When she closes the client-side application/tab, you have nothing to do.

i see we cannot stop a user from leaving when he/she closes the client-side application/tab.
But what if he/she tries to leave the meeting by clikcing the leave meeting button in our application? I'm sure we can hook the muc-occupant-pre-leave event. Can we stop the event then?

**Comment by emrahcom** [comment]
No idea but the modules in this repo doesn't have such a feature. Maybe you can get help from he community forum.
