### ISSUE TITLE
Use another method for ending room after time has elapsed

### ISSUE THREAD

**Issue by swimmwatch** [jitsi-contrib/prosody-plugins#28]
Hi! I am using the [Time Restricted](https://github.com/jitsi-contrib/prosody-plugins/tree/main/time_restricted) plugin and i faced with following problem: my client applications (Jitsi React SDK, Jitsi Flutter SDK) сannot close Jitsi application on "the meeting ended after time has expired" event.  Event [`readyToClose`](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-events/#readytoclose) does not emit when Time Restricted plugin [kicks all room participants](https://github.com/jitsi-contrib/prosody-plugins/blob/f428c6ec696640892e41db7652110c35a796f468/time_restricted/mod_time_restricted.lua#L40).

I have found how [Jitsi Meet handle "End meeting for all"](https://github.com/jitsi/jitsi-meet/blob/36963d6dfb0ec8a7b4d1e208aac2f4aa0f527b3d/resources/prosody-plugins/mod_end_conference.lua#L75) and replaced for loop and `room:set_affiliation` call to `room:destroy` call. And after that client applications can to catch `readyToClose` event when Time Restricted plugin ends meeting.

I suggest to replace for loop and `room:set_affiliation` call to `room:destroy` call.

**Comment by emrahcom** [comment]
Hi @swimmwatch, thank you for your suggestion. Actually I tried `room:destroy` before and it causes the zombie room issue in some conditions. A room which cannot be closed correctly and becomes inaccessible for the next sessions even there is no one inside it.

Therefore this modules kicks everybody outside and lets `prosody` to close the room.

**Comment by swimmwatch** [comment]
@emrahcom can you please tell me if the room-destroyed hook is triggered for zombie rooms?

**Comment by emrahcom** [comment]
No idea. I didn't check it before.

**Comment by emrahcom** [comment]
I think I misused `room:destroy` before and updated the codes to try it again.
