### ISSUE TITLE
Docker Based Jitsi Setup

### ISSUE THREAD

**Issue by DeepJoshi4393** [jitsi-contrib/prosody-plugins#33]
How can I achieve this in a Docker-based Jitsi environment? Also, what do you mean by '{api_prefix}'?

**Comment by shawnchin** [comment]
I'm assuming you're referring to [event_sync](https://github.com/jitsi-contrib/prosody-plugins/tree/main/event_sync).

`api_prefix` refers to the base url for the endpoint that should receive the calls. For example, if want the module to call `https://events.yourapp.com/jitsi/events/room/created` when a room is created, then in the config you would set:
```lua
api_prefix = "https://events.yourapp.com/jitsi"
```

I'm afraid I've never deployed this with with docker-based Jitsi so can't give you exact steps, but there are those in the community that have done so. Perhaps try asking in this thread -- https://community.jitsi.org/t/events-sync-module-does-not-work/132647/6?u=shawn

**Comment by DeepJoshi4393** [comment]
Sorry for not mentioning details earlier. I am trying to integrate the custom prosody module https://github.com/jitsi-contrib/prosody-plugins/tree/main/event_sync with our setup. Could you please help me on that or Is there a way to retrieve all conference details from our server, including the conference name, attendee first names, last names, emails, number of participants, total conference time, start time, end time of the conference, and information for each attendee?

**Comment by shawnchin** [comment]
As long as the lua process can resolve the hostname and reach the service, sure.
