### ISSUE TITLE
Jibri Autostart - Starting with transcription

### ISSUE THREAD

**Issue by dnna** [jitsi-contrib/prosody-plugins#34]
The Jibri Autostart is an amazing plugin that automates a big hassle for our use case.

But these days, it's possible to also launch Jibri with transcription through the UI. Can the same be achieved automatically using the plugin?

**Comment by emrahcom** [comment]
Hi @dnna, I've never tested transcription. So, no idea...
You are talking about recording the session with transcription, right..? Not about starting transcription with `jigasi`...

**Comment by dnna** [comment]
Yes, it apparently sets some sort of room metadata which then causes jicofo to auto-invite jigasi into the room.

In any case, I found a workaround where I hacked jibri autostart and made it invite jigasi independently of the recording. If it's of interest the code I used to invite jigasi was this (just below the part where it sends the iq to invite jibri):
```
local iq = st.iq({
    type = "set",
    id = uuid() .. ":sendIQ",
    from = occupant_jid,
    to = room.jid .. "/focus"
    })
    :tag("dial", {
        xmlns = "urn:xmpp:rayo:1",
        from = "fromnumber",
        to = "jitsi_meet_transcribe"
        }):tag("header", {
            name = "JvbRoomName",
            value = room.jid
        })

module:send(iq)
```

**Comment by damencho** [comment]
The difference between inviting it manully and letting jicofo invite it is that, if the person who turned on subtitles, leaves the meeting, jigasi will detect that nobody is requesting subtitles and will leave. While the other one we call transcriptions, there is a flag in the metadata that transcriptions are requested for this meeting (transcriptions are one more artifact of recording a meeting) and even if nobody wants subtitles, transcriptions are still produced and stored (if that is configured and available in the setup) so they can be added later next to the recording as an artifact of the meeting.
