### ISSUE TITLE
2 muc-room-destroyed events generated by event_sync when used in combination with token_owner_party

### ISSUE THREAD

**Issue by RalphKradle** [jitsi-contrib/prosody-plugins#37]
I have observed the following:

When using the `event_sync` plugin together with the `token_owner_party` plugin `POST ${api_prefix}/events/room/destroyed` is called twice:

1. Immediately after  the last owner has left the room.
2. Again `party_check_timeout` seconds after the last owner left the room.

Is there a way to change this behaviour so that only the 2nd event occurs, as this is what I would logically expect? Right now my workaround is to ignore the 1st event but that's a kludge IMO. Thanks! :)

**Comment by emrahcom** [comment]
I cannot reproduce this issue. `room_destroyed` is only triggered once in Prosody in my tests.

I tested by adding this line:

`module:log("info", "DESTROYED ZZZZZZZZZZZZZ")`

into `room_destroyed` function in the module.

**Comment by RalphKradle** [comment]
I have tested on 3 different machines and am seeing 2 room_destroyed events on all of them. Maybe it's something to do with my setup? Below are excerpts from my Prosody config if that helps:

```
VirtualHost "6cba52c9-5268-4bad-a094-7e41317e774a.konnect-me.info"
    authentication = "token"
    app_id="xxx"
    app_secret="xxx"
    allow_empty_tokens = false

    modules_enabled = {
        "bosh";
        "ping"; -- Enable mod_ping
        "speakerstats";
        "external_services";
        "conference_duration";
        "end_conference";
        "muc_lobby_rooms";
        "muc_breakout_rooms";
        "av_moderation";
        "room_metadata";
    }

Component "conference.6cba52c9-5268-4bad-a094-7e41317e774a.konnect-me.info" "muc"
    restrict_room_creation = true
    storage = "memory"
    modules_enabled = {
        "muc_hide_all";
        "muc_meeting_id";
        "muc_domain_mapper";
        "polls";
        "token_verification";
        "token_affiliation";
        "token_lobby_bypass";
        "token_owner_party";
        "muc_rate_limit";
        "muc_password_whitelist";
    }
    admins = { "focus@auth.6cba52c9-5268-4bad-a094-7e41317e774a.konnect-me.info" }
    muc_password_whitelist = {
        "focus@auth.6cba52c9-5268-4bad-a094-7e41317e774a.konnect-me.info"
    }
    muc_room_locking = false
    muc_room_default_public_jids = true
    party_check_timeout = 20

Component "esync.6cba52c9-5268-4bad-a094-7e41317e774a.konnect-me.info" "event_sync_component"
    muc_component = "conference.6cba52c9-5268-4bad-a094-7e41317e774a.konnect-me.info"
    api_prefix = "http://127.0.0.1:9000"
```

**Comment by RalphKradle** [comment]
Now I am unable to reproduce this and only receive one room_destroyed event directly after the meeting ends. I am not sure if I was testing with an older version previously? Feel like I'm going mad. Anyway, I'll close this issue & modify [mod_token_owner_paty.lua](https://github.com/jitsi-contrib/prosody-plugins/blob/main/token_owner_party/mod_token_owner_party.lua) locally to ensure this works the way I need it to (I am only interested in receiving a room_destroyed event party_check_timeout seconds after the end of the meeting).
