### ISSUE TITLE
Request to https

### ISSUE THREAD

**Issue by coffeduong** [jitsi-contrib/prosody-plugins#5]
Hello,
I'm using event_sync `mod_event_sync_component.lua`. For the `api_prefix`, it's configured with plain http. I've tried https but it didn't work. For ex: `https://my.api.server/api`
I think the main reason here is [line 24 ](https://github.com/jitsi-contrib/prosody-plugins/blob/main/event_sync/mod_event_sync_component.lua#L24)`net.http`doesn't support https.
Probably you can change to  `local https = require 'ssl.https'`
Reference https://stackoverflow.com/a/8289116/4318331

**Comment by coffeduong** [comment]
@emrahcom @shawnchin how do you think?

**Comment by shawnchin** [comment]
How does it fail when you configure `api_prefix` to point to an HTTPS uri?

As far as I can tell, the plugin uses `net.http` from prosody which appears to support https (https://github.com/bjc/prosody/blob/af11afa9c6f3766068d2aa369a7f4c15cbbf1d9a/net/http.lua#L21) and not `socket.http` referenced in the stackoverflow post.

**Comment by coffeduong** [comment]
@shawnchin I can see API response code 0

```
Nov 03 02:51:35 bosh642ff9b9-59ee-497d-a3b8-c3fbabf6b725	info	Authenticated as h23xbt7ayzd50bqw@mydomain.com
Nov 03 02:51:42 event_sync.mydomain.com:event_sync_component	info	Start tracking occupants for demo-book@conference.mydomain.com
Nov 03 02:51:42 event_sync.mydomain.com:event_sync_component	info	New occupant - {"occupant_jid":"h23xbt7ayzd50bqw@mydomain.com/6tjaLMe7","joined_at":1635882702}
Nov 03 02:51:42 event_sync.mydomain.com:event_sync_component	warn	API Response code 0. Will retry after 3s
Nov 03 02:51:42 event_sync.mydomain.com:event_sync_component	warn	API Response code 0. Will retry after 3s
Nov 03 02:51:46 event_sync.mydomain.com:event_sync_component	warn	API Response code 0. Will retry after 3s
Nov 03 02:51:54 event_sync.mydomain.com:event_sync_component	info	Occupant left - {"joined_at":1635882702,"occupant_jid":"h23xbt7ayzd50bqw@mydomain.com/6tjaLMe7","left_at":1635882714}
Nov 03 02:51:54 speakerstats.mydomain.com:speakerstats_component	warn	A module has been configured that triggers external events.
Nov 03 02:51:54 speakerstats.mydomain.com:speakerstats_component	warn	Implement this lib to trigger external events.
Nov 03 02:51:54 event_sync.mydomain.com:event_sync_component	info	Room destroyed - demo-book@conference.mydomain.com
Nov 03 02:51:54 bosh642ff9b9-59ee-497d-a3b8-c3fbabf6b725	info	BOSH client disconnected: session close
Nov 03 02:51:54 event_sync.mydomain.com:event_sync_component	warn	API Response code 0. Will retry after 3s
Nov 03 02:51:54 event_sync.mydomain.com:event_sync_component	warn	API Response code 0. Will retry after 3s
Nov 03 02:51:57 event_sync.mydomain.com:event_sync_component	warn	API Response code 0. Will retry after 3s
```

My configuration
```
Component "event_sync.mydomain.com" "event_sync_component"
    muc_component = "conference.mydomain.com"
    api_prefix = "https://manage.emso.vn/api/man/v1/jitsimeet"
    --retry_count = 5  
    api_retry_delay = 3
```

I've tried curl from Jitsi server and it connects normally

**Comment by coffeduong** [comment]
@shawnchin I can see API Response code 0
```
Nov 03 02:51:35 bosh642ff9b9-59ee-497d-a3b8-c3fbabf6b725	info	Authenticated as h23xbt7ayzd50bqw@mydomain.com
Nov 03 02:51:42 event_sync.mydomain.com:event_sync_component	info	Start tracking occupants for demo-book@conference.mydomain.com
Nov 03 02:51:42 event_sync.mydomain.com:event_sync_component	info	New occupant - {"occupant_jid":"h23xbt7ayzd50bqw@mydomain.com/6tjaLMe7","joined_at":1635882702}
Nov 03 02:51:42 event_sync.mydomain.com:event_sync_component	warn	API Response code 0. Will retry after 3s
Nov 03 02:51:42 event_sync.mydomain.com:event_sync_component	warn	API Response code 0. Will retry after 3s
Nov 03 02:51:46 event_sync.mydomain.com:event_sync_component	warn	API Response code 0. Will retry after 3s
Nov 03 02:51:54 event_sync.mydomain.com:event_sync_component	info	Occupant left - {"joined_at":1635882702,"occupant_jid":"h23xbt7ayzd50bqw@mydomain.com/6tjaLMe7","left_at":1635882714}
Nov 03 02:51:54 speakerstats.mydomain.com:speakerstats_component	warn	A module has been configured that triggers external events.
Nov 03 02:51:54 speakerstats.mydomain.com:speakerstats_component	warn	Implement this lib to trigger external events.
Nov 03 02:51:54 event_sync.mydomain.com:event_sync_component	info	Room destroyed - demo-book@conference.mydomain.com
Nov 03 02:51:54 bosh642ff9b9-59ee-497d-a3b8-c3fbabf6b725	info	BOSH client disconnected: session close
Nov 03 02:51:54 event_sync.mydomain.com:event_sync_component	warn	API Response code 0. Will retry after 3s
Nov 03 02:51:54 event_sync.mydomain.com:event_sync_component	warn	API Response code 0. Will retry after 3s
Nov 03 02:51:57 event_sync.mydomain.com:event_sync_component	warn	API Response code 0. Will retry after 3s
```
My configuration
```
Component "event_sync.mydomain.com" "event_sync_component"
    muc_component = "conference.mydomain.com"
    api_prefix = "https://sub.mydomain.com/api/jitsimeet"
    --retry_count = 5
    api_retry_delay = 3
```

I've tried curl from Jitsi server to the sub.domain.com and it connects normally.
What did I do wrong?

**Comment by coffeduong** [comment]
I can see the `response_body` is `certificate-verify-failed`. I think this the main reason to request to https. But I don't know which certificate, from api_prefix or current Jitsi server?
I've tried command `update-ca-certificates -f` but it doesn't work

**Comment by shawnchin** [comment]
That certainly smells like an issue related to [LetsEncrypt DST Root CA X3 expiration](DST Root CA X3 Expiration). 

Your server certificate is valid, but the lua code is still using old list of CAs to verify certs, and that probably still contains "DST Root CA X3" entry which is now expired. 

What OS are you on?  If Ubuntu/Debian, perhaps try upgrading ca-certificates and libssl packages?

**Comment by shawnchin** [comment]
Btw, I've just tested the module by point api_prefix to a https://webhook.site address and the payload is sent as expected. 

Which means `net.http` should handle HTTPS and you should be good to go once the CA certificates issue is sorted out.

**Comment by coffeduong** [comment]
@shawnchin I'm using Debian 10 buster. Following [Certificate Compatibility](https://letsencrypt.org/docs/certificate-compatibility/) it still support right?
I've tried update openssl
```
root@jitsimeet:/etc/prosody# apt-get install openssl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openssl is already the newest version (1.1.1d-0+deb10u7).
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
```

Set `!mozilla/DST_Root_CA_X3.crt` in `/etc/ca-certificates.conf`

And run `update-ca-certificates -f` 

But the problem's still there. What do you think in this case?

**Comment by emrahcom** [comment]
The related package is ca-certificates

**Comment by coffeduong** [comment]
@emrahcom could you give more detail? Like I said I updated the certificates but it still didn't work

**Comment by shawnchin** [comment]
> Like I said I updated the certificates

When you said you updated, did you mean this?
```
apt-get update
apt-get install --upgrade ca-certificates
```

**Comment by shawnchin** [comment]
Not sure what else to add I'm afraid. Works on ubuntu hosts that I've tested and I don't currently have immediate access to Debian to test.  

Have you tried pointing the plugin to a different HTTPS endpoint (e.g. visit https://webhook.site and get a unique test url) just to quickly work out if the issues is indeed with CA Certificates on host or a legit cert issue on your server?

Also, perhaps check that you have not overriden ssl `capath` in prosody? AFAIK it is possible to configure prosody to use a different trusted cert store, but no idea if this impacts `net.http` calls.

**Comment by coffeduong** [comment]
@shawnchin you're right, the main reason is because of server of `api_prefix`, not the `net.http`

Thank you very much! @shawnchin @emrahcom

**Comment by denis-ionov** [comment]
@coffeduong hello. Did you fix your problem with https in api_prefix? Got the same problem. wget request from prosody container to event routes works (server is in another container), but requests from event_sync component returns code 0 with "connection refused" response body.

**Comment by coffeduong** [comment]
Sorry @denis-ionov , when I worked on this issue, only God & I understand what it did. Now, only God knows 😭 

Just kidding, it will take time for me to check the old project again.

**Comment by shawnchin** [comment]
There should be no issues with HTTPS in api_prefix. 

The one common issue we see when someone has issues (but curl/wget works) is when they rely on /etc/hosts for resolving hostnames. AFAIK the IP resolver behind `net.http` does not use /etc/hosts and so you need to make sure the hostname you specify is resolvable via DNS (or where possible/practical, fallback to using IP in api_prefix).

**Comment by denis-ionov** [comment]
@coffeduong @shawnchin thanks for replies. @shawnchin setting up container ip instead of host at api_prefix makes it work. Thanks again!

**Comment by seferdemirci** [comment]
@shawnchin @emrahcom Sorry for opening the thread again, but If we have to use the domain name instead of the IP address, how can we solve it?

**Comment by alikhancherli** [comment]
Hi,
I have this error `API Response code 0. Will retry after 1s` too. But, I can not fix it. 
Can you help me to fix it?

**Comment by emrahcom** [comment]
Can you simulate the same API call with `curl` on Prosody server?
What is the result in this case?
