### ISSUE TITLE
Typo in the Readme.md

### ISSUE THREAD

**Issue by holema** [jitsi-contrib/prosody-plugins#7]
Thanks for the great plugin.
In the Readme.md of event_sync Dokumentation is an copy/past issue which propably can confuse a little bit. :)

{
  "event_name": "**muc-room-created**", **_must be muc-room-destroyed_**
  "room_name": "catchup",
  "room_jid": "catchup@conference.meet.mydomain.com",
  "created_at": 1625823996,
  "destroyed_at": 1625824035,
  "all_occupants": [
    {
      "name": "James Barrow",
      "email": "j.barrow@domain.com",
      "id": "00380324-a840-400d-880f-7ee0933b7556",
      "occupant_jid": "14f01c40-5195-4a4d-8efb-f58b49d18741@meet.mydomain.com/OWhl8jSh",
      "joined_at": 1625823996,
      "left_at": 1625824035
    }
  ]
}

**Comment by shawnchin** [comment]
Thanks for spotting that. I've raised a PR to get that fixed.
